using Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace Api.Data;

// NOT AUTOGENERATED
public class TelecamContext : DbContext
{
    public TelecamContext(DbContextOptions<TelecamContext> options) : base(options)
    {
    }

    public DbSet<User> Users { get; set; }
    public DbSet<Contact> Contacts { get; set; }
    public DbSet<Message> Messages { get; set; }
    
}